server:
  port: 18080
spring:
  # H2
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  # 시큐리티 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2efadda9384cf916fb6a57298b75698d
            client-secret: KtRoTdoF91i1PUWxbFerMk5e8iaf3cDm
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            redirect-uri: http://localhost:18080/login/oauth2/code/kakao
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id